"""neuralNetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wBIBT9Z6ayl4ZbwKOzY538K5IRHI4Qco
"""

from tensorflow.keras.datasets import mnist
from keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) =  mnist.load_data()

x_train = x_train/255
x_test = x_test/255

y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

y_train[0]

import matplotlib.pyplot as plt
plt.imshow(x_train[5])
plt.title(f"image label = {y_train[5]}")
plt.show()

from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical

model = Sequential([
    Flatten(input_shape = (28,28)), #input layer neuron 784
    Dense(5, activation = 'relu'), #hidden layer 5 neuron
    Dense(10, activation = 'softmax') #output layer 10 neuron
])

model.summary()

model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics= ['accuracy'])

model.fit(x_train, y_train, epochs=5, batch_size=32, verbose=2)

model.evaluate(x_test, y_test)

model.save('mnist.h5')
